# Generated by Django 5.1.5 on 2025-01-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='move_in_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='move_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
