# Generated by Django 5.1.5 on 2025-02-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_alter_tenant_apartment_alter_tenant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='remarks',
            field=models.TextField(blank=True, help_text='Additional details about the tenant.', null=True),
        ),
    ]
